apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xfd5kormw-java-springboot
  janus-idp.io/tekton: xfd5kormw-java-springboot
  backstage.io/kubernetes-id: xfd5kormw-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xfd5kormw-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
